### ISSUE TITLE
Rebuild project website when changes to docs are made

### ISSUE THREAD

**Issue by gmgall** [hiperwalk/hiperwalk#5]
A GitHub Actions workflow that rebuilds the [project website](https://hiperwalk.org/) when changes to files in `docs/` should be created.

**Comment by hiperwalk** [comment]
Commits [5dd67fa](https://github.com/hiperwalk/hiperwalk/commit/5dd67fa6a3fd9b67bd81b60d523215574f26ac93) and [c3cd3e3](https://github.com/hiperwalk/hiperwalk/commit/c3cd3e34b3964ab9ab57d94e3526491ca33e4ba8) add a workflow that rebuild and redeploy https://hiperwalk.org/ when a commit is made in the `master` and `2.0a` branches (but only if a modification is made to `docs/` or `hiperwalk/`).
