### ISSUE TITLE
Low performance for generating animation

### ISSUE THREAD

**Issue by gustavowl** [hiperwalk/hiperwalk#7]
When an generating an animation, the time for adding a new frame to the animation always increases. That is, each iteration is slower than the previous one.

**Comment by gmgall** [comment]
1) The problem doesn't seem to happen when **adding** a new frame but when **saving** an animation.
2) Most of the processing time when saving an animation is spent not by hiperwalk itself but by an external process (`ffmpeg`) used by matplotlib.

I'll go into more detail on why I think so below.

---

# Times saving vs times not saving animations

I ran the code below (based in the code provided by issue #6) changing the number of steps to watch how the times would evolve.

```python
     1  import hiperwalk as hpw
     2  import os
     3  from time import time
     4
     5  g = hpw.Cycle(11)
     6  qw = hpw.ContinuousTime(graph=g, gamma=0.35)
     7  states = qw.simulate(time=(10, 1), initial_state=qw.ket(5))
     8  probs = qw.probability_distribution(states)
     9
    10  print(f'PID: {os.getpid()}')
    11  start = time()
    12  hpw.plot_probability_distribution(probs, animate=True, show=False, filename=None)
    13  print(f'Time elapsed: {time() - start}')
```

Then I ran the code with the parameter `filename='test'` in the function `plot_probability_distribution()` to write the animated gif to `test.gif`.

These were the times:

| steps¹ | time for just adding² | time for saving³ |
|---------|--------------------------|------------------------|
| 10 | 1.2527775764465332 | 11.386841535568237 |
| 20 | 2.3937788009643555 | 34.07587242126465 |
| 30 | 3.7106640338897705 | 78.61413764953613 |
| 40 | 5.187752723693848 | 128.0371913909912 |

¹ line 5 was changed from `hpw.Cycle(11)` to `hpw.Cycle(21)`, `hpw.Cycle(31)` and `hpw.Cycle(41)` and the value of `time` in line 7 was changed from `(10, 1)` to `(20, 1)`, `(30, 1)` and `(40, 1)`

² line 12 was used as shown above: `hpw.plot_probability_distribution(probs, animate=True, show=False, filename=None)`

³ line 12 was used with a value different than `None` for `filename`:  `hpw.plot_probability_distribution(probs, animate=True, show=False, filename='test')`

The times for adding a step seem to be evolving linearly. Saving times seem problematic. 

# Profiling

Using [line_profiler](https://github.com/pyutils/line_profiler) to assess `plot_probability_distribution()`, a clear hotspot appears on line 280 [when calling `save_animation()`](https://github.com/hiperwalk/hiperwalk/blob/master/hiperwalk/plot/_plot.py#L279):

```Timer unit: 1e-06 s

Total time: 13.1321 s
File: /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_plot.py
Function: plot_probability_distribution at line 20

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    20                                           @profile
    21                                           def plot_probability_distribution(
    22                                                   probabilities, plot=None, animate=False, show=True,
    23                                                   filename=None, interval=250, **kwargs):
   201                                           
   202         1          0.9      0.9      0.0      if 'graph' in kwargs:
   203                                                   plot = _default_graph_kwargs(kwargs, plot)
   204                                           
   205         1          0.4      0.4      0.0      if plot is None:
   206         1          0.3      0.3      0.0          plot = 'bar'
   207                                           
   208         1          0.7      0.7      0.0      plot = plot.lower()
   209         1          0.4      0.4      0.0      valid_plots = ['bar', 'line', 'graph', 'histogram', 'plane']
   210                                           
   211         1          0.4      0.4      0.0      if plot not in valid_plots:
   212                                                   raise ValueError(
   213                                                       'Unexpected value for plot:' + str(plot) +
   214                                                       '. One of the following was expected: ' + str(valid_plots)
   215                                                   )
   216                                           
   217                                               # dictionaries for function pointers
   218                                               # preconfiguration: executed once before the loop starts
   219         2          1.1      0.5      0.0      preconfigs = {valid_plots[0]: _preconfigure_plot,
   220         1          0.2      0.2      0.0              valid_plots[1]: _preconfigure_plot,
   221         1          0.2      0.2      0.0              valid_plots[2]: _preconfigure_graph_plot,
   222         1          0.3      0.3      0.0              valid_plots[3]: _preconfigure_plot,
   223         1          0.2      0.2      0.0              valid_plots[4]: _preconfigure_plot}
   224                                               # configuration: executed every iteration before plotting
   225                                               # expects return of fig, ax to be used for animations
   226         2          0.5      0.3      0.0      configs = {valid_plots[0]: _configure_plot_figure,
   227         1          0.2      0.2      0.0              valid_plots[1]: _configure_plot_figure,
   228         1          0.2      0.2      0.0              valid_plots[2]: _configure_graph_figure,
   229         1          0.2      0.2      0.0              valid_plots[3]: _configure_plot_figure,
   230         1          0.2      0.2      0.0              valid_plots[4]: _configure_plane_figure}
   231                                               # plot functions: code for plotting the graph accordingly
   232         1          0.3      0.3      0.0      plot_funcs = {
   233         1          0.3      0.3      0.0          valid_plots[0]: _plot_probability_distribution_on_bars,
   234         1          0.3      0.3      0.0          valid_plots[1]: _plot_probability_distribution_on_line,
   235         1          0.2      0.2      0.0          valid_plots[2]: _plot_probability_distribution_on_graph,
   236         1          0.2      0.2      0.0          valid_plots[3]: _plot_probability_distribution_on_histogram,
   237         1          0.3      0.3      0.0          valid_plots[4]: _plot_probability_distribution_on_plane
   238                                               }
   239                                           
   240                                               # preparing probabilities to shape requested by called functions
   241         1          0.9      0.9      0.0      if len(probabilities.shape) == 1:
   242                                                   probabilities = [probabilities]
   243                                           
   244                                               # passes kwargs by reference to be updated accordingly
   245         1          8.8      8.8      0.0      preconfigs[plot](probabilities, kwargs)
   246                                           
   247         1          0.3      0.3      0.0      if animate:
   248         1          2.2      2.2      0.0          anim = Animation()
   249                                           
   250        12          8.9      0.7      0.0      for i in range(len(probabilities)):
   251                                                   # TODO: set figure size according to graph dimensions
   252                                                   # TODO: check for kwargs
   253        11     368915.2  33537.7      2.8          fig, ax = configs[plot](probabilities.shape[1]) 
   254                                           
   255        11     319866.9  29078.8      2.4          plot_funcs[plot](probabilities[i], ax, **kwargs)
   256                                           
   257        11     443573.0  40324.8      3.4          plt.tight_layout()
   258                                           
   259                                                   # saves or shows image (or both)
   260        11          7.4      0.7      0.0          if not animate:
   261                                                       if filename is not None:
   262                                                           # enumarating the plot
   263                                                           filename_suffix = (
   264                                                               '-' + (len(probabilities)-1)//10 * '0' + str(i)
   265                                                               if len(probabilities) > 1 else ''
   266                                                           )
   267                                                           plt.savefig(filename + filename_suffix)
   268                                                           if not show:
   269                                                               plt.close()
   270                                                       if show:
   271                                                           plt.show()
   272                                           
   273                                                   else:
   274        11     640300.5  58209.1      4.9              anim.add_frame(fig)
   275                                           
   276         1          0.3      0.3      0.0      if animate:
   277         1      26030.9  26030.9      0.2          anim.create_animation(interval)
   278                                           
   279         1          0.5      0.5      0.0          if filename is not None:
   280         1   11333391.9    1e+07     86.3              anim.save_animation(filename)
   281         1          1.4      1.4      0.0          if show:
   282                                                       anim.show_animation()

 13.13 seconds - /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_plot.py:20 - plot_probability_distribution
```

When using the `@profiler` decorator on `save_animation()` and rerunning the results are the following:

```
Timer unit: 1e-06 s

Total time: 10.6746 s
File: /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_animation.py
Function: save_animation at line 131

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   131                                               @profile
   132                                               def save_animation(self, filename):
   165         1          0.7      0.7      0.0          valid_extensions = ['.gif', '.mp4']
   166                                           
   167         1          0.6      0.6      0.0          extension = filename[-4:]
   168         1          0.5      0.5      0.0          if extension not in valid_extensions:
   169         1          0.6      0.6      0.0              filename += '.gif'
   170         1          0.5      0.5      0.0          self.save_path = filename
   171                                           
   172         1   10673543.1    1e+07    100.0          self.plt_anim.save(self.save_path)
   173         1        189.7    189.7      0.0          plt.close()
   174                                           
   175                                                   # by ignoring this condition while using the terminal,
   176                                                   # a non-aborting exception is thrown:
   177                                                   # AttributeError: 'NoneType' object has no attribute 'add_callback'.
   178                                                   # The attributes deleted are needed for saving
   179                                                   # html5 video in jupyter notebooks
   180         1          8.0      8.0      0.0          if not self._is_in_notebook():
   181         1         21.9     21.9      0.0              del self.plt_anim
   182         1          0.4      0.4      0.0              self.plt_anim = None
   183         1        854.4    854.4      0.0              del self.frames
   184         1          0.3      0.3      0.0              self.frames = None

 10.67 seconds - /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_animation.py:131 - save_animation
```

Virtually all of the runtime is used by [a single call of a single method of `matplotlib.animation.FuncAnimation`](https://github.com/hiperwalk/hiperwalk/blob/master/hiperwalk/plot/_animation.py#L171) (line 172).

# External processes

Providing the PID printed by the test script to the `pstree` command it is possible to see that a child process run almost for the whole runtime:

```shell
$ pstree -a 1002325
python generate_lstats.py
  ├─ffmpeg -f rawvideo -vcodec rawvideo -s 1200x1000 -pix_fmt rgba -r 4.0 -loglevel error -i pipe: -filter_complex split [a][b];[a] palettegen [p];[b][p] paletteuse -y test.gif
  │   └─8*[{ffmpeg}]
  └─4*[{python}]
```

---

# Conclusion

Since the hotspot seems to be a single call of a single matplotlib method (that spawns a single external process), it doesn't look like there is a lot of refactoring to be done.

There aren't obvious bottlenecks at the hiperwalk level like unnecessarily creating/destroying objects or slow loops when saving animations. In fact, most of the runtime is not even spent in Python code at all. It is spent by `ffmpeg`.

I'll delve further into the matplotlib documentation to assess whether `matplotlib.animation.FuncAnimation` is ideal for what we are trying to do.

**Comment by gustavowl** [comment]
I took a look into the [`matplotlib.animation`](https://matplotlib.org/stable/api/animation_api.html) docs.

Apparently, `matplotlib.animation.FuncAnimation` should be used when we need only to redraw certain elements, e.g. bars in a bar plot:

> Thus, by managing a saved 'clean' bitmap, we can only re-draw the few artists that are changing at each frame and possibly save significant amounts of time.

In hiperwalk, each frame is generated as a separate image. This was necessary because any plot that used colorbars would not have the expected effect. I am unsure if this is still the case.

It may be a good idea to use `matplotlib.animation.ArtistAnimation` instead. The docs provides almost no detail about this class, except that it is a...
> TimedAnimation subclass that creates an animation by using a fixed set of Artist objects.

However, in the `matplotlib.animation` docs, in the [examples subsection](https://matplotlib.org/stable/api/animation_api.html#id1), `AritstAnimation` is used for [generating an animation using a precomputed list of images](https://matplotlib.org/stable/gallery/animation/dynamic_image.html). Which is more suitable for our code.

Another option is to manually save each frame into a temporary directory and then manually generate an animation from them.

**Comment by gmgall** [comment]
I've being doing some tests with different dpis, [writers](https://matplotlib.org/stable/tutorials/introductory/animation_tutorial.html#animation-writers) and resolutions without too much improvement on write times.

I will give `ArtistAnimation` a try now.

**Comment by gmgall** [comment]
> In hiperwalk, each frame is generated as a separate image. This was necessary because any plot that used colorbars would not have the expected effect. I am unsure if this is still the case.

It looks like a good idea since the only thing [`func`](https://github.com/hiperwalk/hiperwalk/blob/master/hiperwalk/plot/_animation.py#L100) is doing (the 2nd parameter to `FuncAnimation`) is drawing an image to the `Axes`, if I understood correctly.

It's almost like hiperwalk forces the behavior of `ArtistAnimation` with `FuncAnimation`, if that makes sense.

> However, in the `matplotlib.animation` docs, in the [examples subsection](https://matplotlib.org/stable/api/animation_api.html#id1), `AritstAnimation` is used for [generating an animation using a precomputed list of images](https://matplotlib.org/stable/gallery/animation/dynamic_image.html). Which is more suitable for our code.

I reran the tests from my [first reply](https://github.com/hiperwalk/hiperwalk/issues/7#issuecomment-1688940959) [here]() after the test changes in gmgall/hiperwalk@4f98d1b and save speeds have improved a lot.

| steps | time for just adding | time for saving |
|---------|--------------------------------|-------------------------|
|10 | 1.3454062938690186 | 3.182034730911255 |
|20 | 2.5065243244171143 | 6.1487884521484375 |
|30 | 4.088005304336548 | 8.93243408203125 |
|40 | 5.6711413860321045 | 12.329192161560059 |

**Comment by gustavowl** [comment]
Please run some tests before a PR to assert behaviour.

- Run all tests in [examples](https://github.com/hiperwalk/hiperwalk/tree/master/examples) via terminal.
- Run all tests in [examples](https://github.com/hiperwalk/hiperwalk/tree/master/examples) in a jupyter notebook.
- Run the following tests in terminal *and* jupyter notebook. Before execution, substitute ``time`` value in [line 12 of coined diagonal grid example](https://github.com/hiperwalk/hiperwalk/blob/master/examples/coined-diagonal-grid.py#L12) to ``time=(dim // 2, 1)`` and add the following arguments in line 14:
  - `animate=False, rescale=False`: should plot multiple figures and the colorbar should range from 0 to 1 in every figure.
  - `animate=False, rescale=True`: should plot multiple figures and the colorbar should range from 0 to the max probability in every figure.
  - `animate=True, rescale=False`: should show animation and the colorbar should range from 0 to 1 in every frame.
  - `animate=True, rescale=True`: should show animation and the colorbar should range from 0 to the max probability in every frame.
- Run all the previous tests but using a generic graph instead. For example, create a graph with networkx. Then, get its adjacency matrix `adj`. Create a generic hiperwalk graph (`g = hpw.Graph(adj)`). Run a simulation with multiple steps and calculate the probability distribution `prob_dist`. Plot the probability distribution passing the graph and additional args (`hpw.plot_probability_distribution(prob_dist, graph=g, animate=[False|True], rescale=[False|True])`). The same results are expected. The two scenarios must be tested because the plotting is delegated to different libraries.

**Comment by gmgall** [comment]
>  * Run the following tests in terminal _and_ jupyter notebook. Before execution, substitute `time` value in [line 12 of coined diagonal grid example](https://github.com/hiperwalk/hiperwalk/blob/master/examples/coined-diagonal-grid.py#L12) to `time=(dim // 2, 1)` and add the following arguments in line 14:

I'll report the results on shell first.

>       
>  * `animate=False, rescale=False`: should plot multiple figures and the colorbar should range from 0 to 1 in every figure.

It seems to be working. Multiple windows with images are open, one after another. All of them seems to have a scale ranging from 0 to 1 on the right side of the image. Since a lot of images are generated, I didn't check them all this way (with `show=True`).

Using `show=False` and `filename='test'` to write files on disc, I get the results in this gist: https://gist.github.com/gmgall/ca2235bf88af763a107da1b21b6d822d/

>  * `animate=False, rescale=True`: should plot multiple figures and the colorbar should range from 0 to the max probability in every figure.

It seems to be working. Multiple windows with images are open, one after another. The first one has a scale ranging from 0 to 1 on the right side. The subsequent images have a scale ranging from 0 to a value smaller than 1. Since a lot of images are generated, I didn't check them all this way (with `show=True`).

Using `show=False` and `filename='test'` to write files on disc, I get the results in this gist: https://gist.github.com/gmgall/0e4a8fe05972d5b06d984f3692eae1e2

> * `animate=True, rescale=False`: should show animation and the colorbar should range from 0 to 1 in every frame.

It seems to be working. A single window with the animation is open. The scale on the right always ranges from 0 to 1.

When `filename='test'` and `show=False`  the `test.gif` written on disc is the one below:

![test](https://github.com/hiperwalk/hiperwalk/assets/973834/71c8545c-c320-4d46-ab13-4eb4650113ee)

> * `animate=True, rescale=True`: should show animation and the colorbar should range from 0 to the max probability in every frame.

It seems to be working. A single window with the animation is open. The scale on the right always ranges from 0 to 1 in the first frame and from 0 to <1 in subsequent frames.

When `filename='test'` and `show=False`  the `test.gif` written on disc is the one below:

![test](https://github.com/hiperwalk/hiperwalk/assets/973834/d987696e-70b3-4a59-8dc8-782922cf271f)

# :stopwatch: Performance data

Using

```python
start = time()
hpw.plot_probability_distribution(prob, graph=grid, ...)
print(f'Time elapsed: {time() - start}')
```

to measure the time spent by `hpw.plot_probability_distribution()` the results were the following:

| Branch                            | `animate=True, rescale=False, filename='test', show=False` | `animate=True, rescale=True, filename='test', show=False` |
|-----------------------------|----------------------------------------------------------|---------------------------------------------------------|
| gmgall/hiperwalk@abf6e53    | 48.25713515281677                                        | 52.723119258880615                                      |
| hiperwalk/hiperwalk@8330b87 | 319.957058429718                                         | 318.50159883499146

**Comment by gmgall** [comment]
:warning: Sometimes `coined-diagonal-grid.py` ends with a non-zero exit code and an error like the one below:

```
ICE default IO error handler doing an exit(), pid = 98839, errno = 32
```

This happens on hiperwalk/hiperwalk@8330b87 and gmgall/hiperwalk@4f98d1b when writing animations **and** individual frames. The problem seems to occur only when generating a lot of steps e.g. I never had this error with 10 steps.

We're not alone though: give a look at issues matplotlib/matplotlib#23369 and vim/vim#156.

One issue cite XFCE and the other cite Xubuntu. I still need to check if it occurs in Ubuntu (Unity / GNOME).

**Comment by gustavowl** [comment]
Comments about the [first comment](https://github.com/hiperwalk/hiperwalk/issues/7#issuecomment-1700433197): excellent. The output images/animations are as expected. The following tests still remain.

- [ ] Run the same tests on the jupyter notebook
- [ ] Run the same tests using `hiperwalk.Graph` instead of `hiperwalk.Grid` . This should use NetworkX to plot (instead of matplotlib). Hence any problem with the colorbar may appear.

About the second comment: please open another hiperwalk issue referring the matplotlib and vim issues.

**Comment by gmgall** [comment]
Running the following modified version of `coined-diagonal-grid.py` on a Jupyter notebook

```python
import hiperwalk as hpw
import numpy as np
from time import time

dim = 121
grid = hpw.Grid(dim, diagonal=True)
center = np.array([dim // 2, dim // 2])
dtqw = hpw.Coined(grid, shift='persistent', coin='grover')
psi0 = dtqw.state([0.5, (center, center + (1, 1))],
                  [-0.5, (center, center + (1, -1))],
                  [-0.5, (center, center + (-1, 1))],
                  [0.5, (center, center + (-1, -1))])
psi_final = dtqw.simulate(time=(dim // 2, 1), initial_state=psi0, hpc=False)
prob = dtqw.probability_distribution(psi_final)

start = time()
hpw.plot_probability_distribution(prob, graph=grid, animate=True, rescale=False, filename='test', show=False)
print(f'Time elapsed: {time() - start}')

start = time()
hpw.plot_probability_distribution(prob, graph=grid, animate=True, rescale=True, filename='test_rescale', show=False)
print(f'Time elapsed: {time() - start}')
```

the `gif` files written to disk when in gmgall/hiperwalk@4f98d1b  are the following:

![test](https://github.com/hiperwalk/hiperwalk/assets/973834/bfa8853e-2c05-47cb-ad10-b26eb3de4830)
![test_rescale](https://github.com/hiperwalk/hiperwalk/assets/973834/e3e6b303-f3f5-4c31-bd5e-cbf396a32e4d)

and the `gif` files written to disk when in hiperwalk/hiperwalk@8330b87  are the following:

![test](https://github.com/hiperwalk/hiperwalk/assets/973834/9b571798-2d31-4a89-86d6-1cb4b877a25b)
![test_rescale](https://github.com/hiperwalk/hiperwalk/assets/973834/dcf2ed1c-d267-4d82-944b-7ff77ed7f0e2)

The times for writing the animation files are similar but slightly slower than when running on shell.

| Branch                            | `animate=True, rescale=False, filename='test', show=False` | `animate=True, rescale=True, filename='test_rescale', show=False` |
|-----------------------------|----------------------------------------------------------|---------------------------------------------------------|
| gmgall/hiperwalk@4f98d1b    | 53.15557789802551 | 53.89512515068054 |
| hiperwalk/hiperwalk@8330b87 | 358.80299711227417 | 355.8999390602112 |

**Comment by gmgall** [comment]
Using `show=True` seems to work fine.

https://github.com/hiperwalk/hiperwalk/assets/973834/e82b400f-d674-4061-b566-601c7115c8e7

**Comment by gmgall** [comment]
```python
import hiperwalk as hpw
import os
import networkx as nx
from time import time

ladder = nx.ladder_graph(10)
print(type(ladder))
adj = nx.adjacency_matrix(ladder)
print(type(adj))
g = hpw.Graph(adj)
print(type(g))
qw = hpw.ContinuousTime(graph=g, gamma=0.35)
states = qw.simulate(time=(50, 1), initial_state=qw.ket(5))
probs = qw.probability_distribution(states)

print(f'PID: {os.getpid()}')
start = time()
hpw.plot_probability_distribution(probs, animate=True, show=False, filename='test')
print(f'Time elapsed: {time() - start}')
```

Is something like the snippet above enough to test the [second item](https://github.com/hiperwalk/hiperwalk/issues/7#issuecomment-1701712272)?

Running it yields the following results on the shell:

```
<class 'networkx.classes.graph.Graph'>
<class 'scipy.sparse._arrays.csr_array'>
<class 'hiperwalk.graph.graph.Graph'>
PID: 2288535
Time elapsed: 24.489588260650635
```

and writes the following `gif`* file:

![test](https://github.com/hiperwalk/hiperwalk/assets/973834/2478d3ee-b498-40e2-8d73-39982bd71105)

:warning: * both write the same file (`diff`ing them shows no differences between the `gif` files written to disc)

**Comment by gustavowl** [comment]
Almost sufficient. The graph must be specified for the tests. Use
```python
hpw.plot_probability_distribution(probs, graph=g, animate=True, show=False, filename='test')
```
instead.

**Comment by gmgall** [comment]
Using

```python
import hiperwalk as hpw
import os
import networkx as nx
from time import time

ladder = nx.ladder_graph(10)
print(type(ladder))
adj = nx.adjacency_matrix(ladder)
print(type(adj))
g = hpw.Graph(adj)
print(type(g))
qw = hpw.ContinuousTime(graph=g, gamma=0.35)
states = qw.simulate(time=(50, 1), initial_state=qw.ket(5))
probs = qw.probability_distribution(states)

print(f'PID: {os.getpid()}')
start = time()
hpw.plot_probability_distribution(probs, graph=g, animate=True, show=False, filename='test')
print(f'Time elapsed: {time() - start}')
```

the `gif` file written by gmgall/hiperwalk@4f98d1b and by hiperwalk/hiperwalk@8330b87 were the same (`diff`ing them shows no differences).

Here it is: 
![test_artst](https://github.com/hiperwalk/hiperwalk/assets/973834/ffb9ada8-cf5f-447a-8bd8-17883d9cbece)

# :stopwatch: Performance data
| Branch                            | `graph=g, animate=True, show=False, filename='test'` |
|-----------------------------|----------------------------------------------------------|
| gmgall/hiperwalk@4f98d1b    | 19.08654022216797 |
| hiperwalk/hiperwalk@8330b87 | 261.68402552604675 |

**Comment by gustavowl** [comment]
Excellent. Now the last one: run the same test with `rescale=True` .

**Comment by gmgall** [comment]
Using

```python
import hiperwalk as hpw
import os
import networkx as nx
from time import time

ladder = nx.ladder_graph(10)
print(type(ladder))
adj = nx.adjacency_matrix(ladder)
print(type(adj))
g = hpw.Graph(adj)
print(type(g))
qw = hpw.ContinuousTime(graph=g, gamma=0.35)
states = qw.simulate(time=(50, 1), initial_state=qw.ket(5))
probs = qw.probability_distribution(states)

print(f'PID: {os.getpid()}')
start = time()
hpw.plot_probability_distribution(probs, graph=g, animate=True, rescale=True, show=False, filename='test')
print(f'Time elapsed: {time() - start}')
```

the `gif` file written by gmgall/hiperwalk@4f98d1b and by hiperwalk/hiperwalk@8330b87 were the same (`diff`ing them shows no differences).

Here it is: 
![test_artst](https://github.com/hiperwalk/hiperwalk/assets/973834/d389a340-1126-4f32-a2e6-ab697b1aadb1)

The information printed on shell is the following:

```
#######################
Continuing without hpc.
#######################

  warn(PYNEBLINA_IMPORT_ERROR_MSG)
<class 'networkx.classes.graph.Graph'>
<class 'scipy.sparse._arrays.csr_array'>
<class 'hiperwalk.graph.graph.Graph'>
```


# :stopwatch: Performance data
| Branch                            | `graph=g, animate=True, rescale=True, show=False, filename='test'` |
|-----------------------------|----------------------------------------------------------|
| gmgall/hiperwalk@4f98d1b    | 19.27019500732422 |
| hiperwalk/hiperwalk@8330b87 | 248.25212454795837 |

**Comment by gustavowl** [comment]
Excellent! Please make a PR.

I'm going to keep this issue open for further improvements.

**Comment by gmgall** [comment]
I'll report below the results of some benchmarks of the most recent implementation of the animations generation logic.

# Times saving vs times not saving animations

I've rerun the code in the [Aug 22 comment](https://github.com/hiperwalk/hiperwalk/issues/7#issuecomment-1688940959) to measure the behavior just adding more frames vs the behavior adding more frames **and** saving the animation to a file.

The results were the following:

|steps¹|time for just adding²|time for saving³|
|--------|--------------------------|---------------------|
|10|0.17957496643066406|1.090562105178833|
|20|0.202620267868042|1.8090264797210693|
|30|0.21750402450561523|2.795325517654419|
|40|0.28695011138916016|3.6429390907287598|

¹ line 5 was changed from `hpw.Cycle(11)` to `hpw.Cycle(21)`, `hpw.Cycle(31)` and `hpw.Cycle(41)` and the value of time in line 7 was changed from `(10, 1)` to `(20, 1)`, `(30, 1)` and `(40, 1)`

² line 12 was used as shown above: `hpw.plot_probability_distribution(probs, animate=True, show=False, filename=None)`

³ line 12 was used with a value different than `None` for `filename`: `hpw.plot_probability_distribution(probs, animate=True, show=False, filename='test')`

Times seem to be behaving much better now, including the time to save the animation to a file.

# Profiling

Again using [line_profiler](https://github.com/pyutils/line_profiler) to assess `plot_probability_distribution()`, a clear hotspot appears. This time on line 310 [when calling save()](https://github.com/hiperwalk/hiperwalk/blob/master/hiperwalk/plot/_plot.py#L309), a method from the `anim` [matplotlib.animation.FuncAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html#matplotlib.animation.FuncAnimation) instance:

```
Total time: 4.23041 s
File: /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_plot.py
Function: plot_probability_distribution at line 20

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    20                                           @profile
    21                                           def plot_probability_distribution(
    22                                                   probabilities, plot=None, animate=False, show=True,
    23                                                   filename=None, interval=250, **kwargs):
   202         1          2.2      2.2      0.0      if 'graph' in kwargs:
   203                                                   plot = _default_graph_kwargs(kwargs, plot)
   204                                           
   205         1          1.0      1.0      0.0      if plot is None:
   206         1          0.7      0.7      0.0          plot = 'bar'
   207                                           
   208         1          2.6      2.6      0.0      plot = plot.lower()
   209         1          1.6      1.6      0.0      valid_plots = ['bar', 'line', 'graph', 'histogram', 'plane']
   210                                           
   211         1          1.1      1.1      0.0      if plot not in valid_plots:
   212                                                   raise ValueError(
   213                                                       'Unexpected value for plot:' + str(plot) +
   214                                                       '. One of the following was expected: ' + str(valid_plots)
   215                                                   )
   216                                           
   217                                               # dictionaries for function pointers
   218                                               # preconfiguration: executed once before the loop starts
   219         2          3.5      1.7      0.0      preconfigs = {valid_plots[0]: _preconfigure_plot,
   220         1          0.9      0.9      0.0              valid_plots[1]: _preconfigure_plot,
   221         1          1.1      1.1      0.0              valid_plots[2]: _preconfigure_graph_plot,
   222         1          1.0      1.0      0.0              valid_plots[3]: _preconfigure_plot,
   223         1          0.7      0.7      0.0              valid_plots[4]: _preconfigure_plot}
   224                                               # configuration: executed every iteration before plotting
   225                                               # expects return of fig, ax to be used for animations
   226         2          2.8      1.4      0.0      configs = {valid_plots[0]: _configure_plot_figure,
   227         1          0.7      0.7      0.0              valid_plots[1]: _configure_plot_figure,
   228         1          0.7      0.7      0.0              valid_plots[2]: _configure_graph_figure,
   229         1          0.7      0.7      0.0              valid_plots[3]: _configure_plot_figure,
   230         1          0.7      0.7      0.0              valid_plots[4]: _configure_plane_figure}
   231                                               # plot functions: code for plotting the graph accordingly
   232         1          1.1      1.1      0.0      plot_funcs = {
   233         1          0.9      0.9      0.0          valid_plots[0]: _plot_probability_distribution_on_bars,
   234         1          0.9      0.9      0.0          valid_plots[1]: _plot_probability_distribution_on_line,
   235         1          0.7      0.7      0.0          valid_plots[2]: _plot_probability_distribution_on_graph,
   236         1          0.7      0.7      0.0          valid_plots[3]: _plot_probability_distribution_on_histogram,
   237         1          1.1      1.1      0.0          valid_plots[4]: _plot_probability_distribution_on_plane
   238                                               }
   239                                           
   240         1          1.3      1.3      0.0      update_animation = {
   241         1          0.7      0.7      0.0          valid_plots[0]: _update_animation_bars,
   242         1          0.9      0.9      0.0          valid_plots[1]: _update_animation_line,
   243         1          1.0      1.0      0.0          valid_plots[2]: _update_animation_graph,
   244         1          0.8      0.8      0.0          valid_plots[3]: _update_animation_bars,
   245         1          0.7      0.7      0.0          valid_plots[4]: None
   246                                               }
   247                                           
   248                                               # preparing probabilities to shape requested by called functions
   249         1          2.7      2.7      0.0      if len(probabilities.shape) == 1:
   250                                                   probabilities = np.array([probabilities])
   251                                           
   252                                               # passes kwargs by reference to be updated accordingly
   253         1         36.7     36.7      0.0      preconfigs[plot](probabilities, kwargs)
   254                                           
   255         1          0.9      0.9      0.0      if not animate:
   256                                                   for i in range(len(probabilities)):
   257                                                       # TODO: set figure size according to graph dimensions
   258                                                       # TODO: check for kwargs
   259                                                       fig, ax = configs[plot](probabilities.shape[1]) 
   260                                           
   261                                                       plot_funcs[plot](probabilities[i], ax, **kwargs)
   262                                           
   263                                                       plt.tight_layout()
   264                                           
   265                                                       # saves or shows image (or both)
   266                                                       if filename is not None:
   267                                                           filename_suffix = str(i).zfill(
   268                                                                   len(str(len(probabilities) - 1)))
   269                                                           plt.savefig(filename + '-' + filename_suffix)
   270                                                           if not show:
   271                                                               plt.close()
   272                                                       if show:
   273                                                           plt.show()
   274                                           
   275                                               else:
   276         1     256113.5 256113.5      6.1          fig, ax = configs[plot](probabilities.shape[1]) 
   277                                           
   278         1          0.4      0.4      0.0          if plot == 'plane':
   279                                                       from functools import partial
   280                                                       surf, cbar = plot_funcs[plot](probabilities[0], ax,
   281                                                                                     **kwargs)
   282                                           
   283                                                       anim = FuncAnimation(
   284                                                               fig,
   285                                                               partial(plot_funcs[plot],
   286                                                                       ax=ax,
   287                                                                       surf=surf,
   288                                                                       cbar=cbar,
   289                                                                       **kwargs),
   290                                                               frames=probabilities)
   291         1          0.3      0.3      0.0          elif plot == 'graph':
   292                                                       from functools import partial
   293                                                       ax, cbar = plot_funcs[plot](probabilities[0], ax,
   294                                                                                   **kwargs)
   295                                           
   296                                                       anim = FuncAnimation(
   297                                                               fig,
   298                                                               partial(plot_funcs[plot], ax=ax, cbar=cbar, **kwargs),
   299                                                               frames=probabilities)
   300                                                   else:
   301         1      45264.8  45264.8      1.1              artists = plot_funcs[plot](probabilities[0], ax, **kwargs)
   302         2        114.2     57.1      0.0              anim = FuncAnimation(
   303         1          0.2      0.2      0.0                      fig,
   304         1          0.5      0.5      0.0                      update_animation[plot],
   305         1          0.2      0.2      0.0                      frames=probabilities,
   306         2          0.7      0.3      0.0                      fargs=(artists,
   307         1          0.4      0.4      0.0                             ax if 'min_prob' not in kwargs else None))
   308                                           
   309         1          0.3      0.3      0.0          if filename is not None:
   310         1    3928835.2    4e+06     92.9              anim.save(filename)
   311         1          1.2      1.2      0.0          if show:
   312                                                       if _is_in_notebook():
   313                                                           from IPython import display
   314                                           
   315                                                           # embedding animation in jupyter notebook
   316                                                           video = anim.to_html5_video()
   317                                                           html = display.HTML(video)
   318                                                           display.display(html)
   319                                           
   320                                                           plt.close()
   321                                                       else:
   322                                                           plt.show()

  4.23 seconds - /home/guilherme/hdd/hiperwalk/hiperwalk/plot/_plot.py:20 - plot_probability_distribution
```
# `rescale=False` vs `rescale=True`

Using the code from the [Sep 1 comment](https://github.com/hiperwalk/hiperwalk/issues/7#issuecomment-1703490592), the following 2 files were written:

![without rescalling](https://github.com/hiperwalk/hiperwalk/assets/973834/d2c229c8-1024-4cec-8435-63c63a0fbed8)
![with rescale](https://github.com/hiperwalk/hiperwalk/assets/973834/0486c74c-dc45-4970-8d86-5c25c408c887)

The times for saving the files were similar but the file sizes weren't.

|`rescale`|time elapsed (s)|file size|
|-|------------------|----------|
|`False`|67.21407437324524|293K|
|`True`|74.03113508224487|2,4M|
