### ISSUE TITLE
Update development documentation

### ISSUE THREAD

**Issue by gmgall** [hiperwalk/hiperwalk#9]
The [development documentation](https://hiperwalk.org/docs/latest/development/index.html) lists 4 packages as required for hiperwalk development: `numpy`, `scipy`, `networkx` and `matplotlib`.

However, hiperwalk in a virtual environment with only these 4 packages installed cannot use some of the plotting functionality due to the lack of dependencies.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/hiperwalk/hiperwalk/plot/_plot.py", line 281, in plot_probability_distribution
    anim.show_animation()
  File "/home/ubuntu/hiperwalk/hiperwalk/plot/_animation.py", line 237, in show_animation
    self._show_animation_terminal()
  File "/home/ubuntu/hiperwalk/hiperwalk/plot/_animation.py", line 242, in _show_animation_terminal
    from gi import require_version
ModuleNotFoundError: No module named 'gi'
```

If the virtual environment is created with access to system* packages (with the `--system-site-packages` flag), the above error does not occur.

```shell
ubuntu@ubuntu:~$ python3 -m venv --system-site-packages ~/hiperwalk-venv
ubuntu@ubuntu:~$ source ~/hiperwalk-venv/bin/activate
(hiperwalk-venv) ubuntu@ubuntu:~$ python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> # NO ERROR
```

[Development documentation](https://hiperwalk.org/docs/latest/development/index.html) should ideally list every package required for development in a clean virtual environment or at least instruct the use of the `--system-site-packages` flag.

*:warning: Tested on Ubuntu 20.04.6 LTS (focal).

**Comment by gustavowl** [comment]
This is not an issue anymore.
